from domain.entities.Animal import Animal


class IAnimalRepository:
    def save(self, animal: Animal) -> None: ...
    def get_by_id(self, animal_id: str) -> Animal: ...
    def delete(self, animal_id: str) -> None: ...
    def get_all(self) -> list[Animal]: ...