from domain.entities.Enclosure import Enclosure


class IEnclosureRepository:
    def save(self, enclosure: Enclosure) -> None: ...
    def get_by_id(self, enclosure_id: str) -> Enclosure: ...
    def get_all(self) -> list[Enclosure]: ...